### ISSUE TITLE
When using a workflow created by default CodeQL is used, starter java and javascript packs are not found

### ISSUE THREAD

**Issue by tspascoal** [GitHubSecurityLab/CodeQL-Community-Packs#28]
The languages as automatically filled in by the [codeql starter workflow](https://github.com/actions/starter-workflows/blob/main/code-scanning/codeql.yml), now uses `java-kotlin` and `javascript-typescript` instead of `java` and `javascript`  like it used to so

(workflow snippet of a repo that has both java and javascript languages)

```yml
 strategy:
      fail-fast: false
      matrix:
        language: [ 'java-kotlin', 'javascript-typescript' ]
        # CodeQL supports [ 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift' ]
        # Use only 'java-kotlin' to analyze code written in Java, Kotlin or both
        # Use only 'javascript-typescript' to analyze code written in JavaScript, TypeScript or both
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
```

So when adding a pack with
```
packs: githubsecuritylab/codeql-${{ matrix.language }}-queries
```

the workflow fails since it can't find the packs
```
rror: Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.15.2/x64/codeql/codeql database init --db-cluster /home/runner/work/_temp/codeql_databases --source-root=/home/runner/work/tspascoal-repro-pack/tspascoal-repro-pack --extractor-include-aliases --language=javascript --codescanning-config=/home/runner/work/_temp/user-config.yaml --calculate-language-specific-baseline --sublanguage-file-coverage". Exit code was 2 and error was: A fatal error occurred: 'githubsecuritylab/codeql-javascript-typescript-queries' not found in the registry 'https://ghcr.io/v2/'. See the logs for more details.
```

Can we publish the packs with both the old as well as the _new_ language name so it supports both old and new workflow files?

Haven't checked if `c-cpp` also changed or it has been like that all along
